version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: kerem
      POSTGRES_PASSWORD: kerem
      POSTGRES_DB: kerem
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

 app:
    build: .
    container_name: wb_service
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://wb_user:wb_password@db:5432/wb_db
      WB_API_KEY: eyJhbGciOiJFUzI1NiIsImtpZCI6IjIwMjQxMDE2djEiLCJ0eXAiOiJKV1QifQ.eyJlbnQiOjEsImV4cCI6MTc0NjA2ODAxNywiaWQiOiIwMTkyZGRlYS1mOWU2LTcxNzItODk0Ny1iMjE1Y2I5MmU5NDgiLCJpaWQiOjQ1OTExNjA5LCJvaWQiOjExMzA0NiwicyI6MTA3Mzc0MTgzMiwic2lkIjoiOTMyYzE3NmEtNTA4NS01YzZmLWJjMzMtNGU4NGNkZjU4ZDdlIiwidCI6ZmFsc2UsInVpZCI6NDU5MTE2MDl9.l2C-kGr-1YptJ5iyp_q1RYSxDOgENHXfGepnmo709g2UsGDnT90NnBt5K-nVLVH14XaEFi81dcmeZvF6qz-oxQ
    ports:
      - "3000:3000"

  volumes:
  postgres_data: